// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClHcRHIKX1s9LY4eebz-v0Ayrvvi2jCvA',
    appId: '1:740596231276:web:5eff44265943ef22c2fc49',
    messagingSenderId: '740596231276',
    projectId: 'saferoute-a872e',
    authDomain: 'saferoute-a872e.firebaseapp.com',
    storageBucket: 'saferoute-a872e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCPBkGWTHy5FY8tCYk3Snap7QAjRMRvek',
    appId: '1:740596231276:android:9c279ac859893f93c2fc49',
    messagingSenderId: '740596231276',
    projectId: 'saferoute-a872e',
    storageBucket: 'saferoute-a872e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJxp5NCdSNVXfodVDdjxn6ZjpDXNrtSCo',
    appId: '1:740596231276:ios:8bdc19d94deea755c2fc49',
    messagingSenderId: '740596231276',
    projectId: 'saferoute-a872e',
    storageBucket: 'saferoute-a872e.firebasestorage.app',
    iosBundleId: 'com.example.saferoute',
  );
}
